/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    FindCard: typeof import('./src/components/FindCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveCardDialog: typeof import('./src/components/SaveCardDialog.vue')['default']
    ViewCard: typeof import('./src/components/ViewCard.vue')['default']
  }
}
